### ISSUE TITLE
[Bug] build with full_build.yaml fails with apt error

### ISSUE THREAD

**Issue by z-bsod** [telekom-mms/docker-management-container#132]
### Description

the build with the full_build.yaml fails due to what seems like a missing package

### Reproduction steps

1. try to build the container with the "full" configuration
2. get an error message

### Current Behavior

currently the build fails due to the missing package

### Expected Behavior

the package should be removed from the packages list. if this is required it needs to be added another way (e.g. as a binary to download)

### Additional information

example of the CI run with this error: https://github.com/telekom-mms/docker-management-container/actions/runs/9552431823/job/26329007527#step:6:1317

the package in the configuration: https://github.com/telekom-mms/docker-management-container/blob/main/examples/full_build.yaml#L9

**Comment by michaelamattes** [comment]
solved with version 3.3.2
